### ISSUE TITLE
Some issues with knative, contour and flux packages reconciling

### ISSUE THREAD

**Issue by Analect** [vrabbi/tap-oss#1]
First of all, thanks for your efforts with this repo.

This could be down to some  bad values getting passed by me in the `tap-oss-values.yaml` file, but I wanted to at least get to the bottom of this.  I'm running this on a local TCE cluster (docker).

```
dev/tce/tap-oss$ tanzu package install tap -n tap-oss -p tap-install.tap.oss -v 0.1.0 -f tap-oss-values.yaml
/ Installing package 'tap-install.tap.oss' 
| Getting namespace 'tap-oss' 
| Getting package metadata for 'tap-install.tap.oss' 
| Creating service account 'tap-tap-oss-sa' 
| Creating cluster admin role 'tap-tap-oss-cluster-role' 
| Creating cluster role binding 'tap-tap-oss-cluster-rolebinding' 
| Creating secret 'tap-tap-oss-values' 
- Creating package resource 
\ Package install status: Reconciling 

 Added installed package 'tap' in namespace 'tap-oss'

~/dev/tce/tap-oss$ kubectl get pkgi -n tap-oss
NAME                     PACKAGE NAME                     PACKAGE VERSION   DESCRIPTION                                                            AGE
cartographer             cartographer.tap.oss             0.2.1             Reconcile succeeded                                                    16h
cert-manager             cert-manager.tap.oss             1.6.1             Reconcile succeeded                                                    16h
contour                  contour.tap.oss                  1.19.1            Reconciling                                                            16h
dev-ns-preperation       dev-ns-preperation.tap.oss       0.1.0             Reconcile succeeded                                                    16h
flux-source-controller   flux-source-controller.tap.oss   0.21.1            Reconciling                                                            16h
knative                  knative-serving.tap.oss          1.0.0             Reconcile failed: Error (see .status.usefulErrorMessage for details)   16h
kpack                    kpack.tap.oss                    0.5.0             Reconcile succeeded                                                    16h
kpack-config             kpack-config.tap.oss             0.5.0             Reconcile succeeded                                                    16h
ootb-supply-chains       ootb-supply-chains.tap.oss       0.1.0             Reconcile succeeded                                                    16h
tap                      tap-install.tap.oss              0.1.0             Reconcile succeeded                                                    16h
tekton-pipelines         tekton.tap.oss                   0.32.1            Reconcile succeeded                                                    16h

```

Here is an anonymized tap-oss-values.yaml I'm using.  Under knative, I switched to using `type: nip.io`, since this will be running locally.  That suggested leaving `name` field empty, but that caused an error when applying this yaml, so I used double-quotes to simulate a blank value.

```
cat <<EOF > tap-oss-values.yaml
kpack:
  kp_default_repository: ghcr.io/my-gh-username
  kp_default_repository_password: ghp_my-github-PAT-xxxxiXzAd
  kp_default_repository_username: my-gh-username
kpack_config:
  builder:
    tag: ghcr.io/my-gh-username/builder-tap-oss
knative:
  domain:
    name: ""
    type: nip.io
dev_ns_preperation:
  registry:
    username: my-gh-username
    password: ghp_my-github-PAT-xxxxiXzAd
    server: ghrc.io
  namespaces:
  - name: "default"
    exists: true
    createPipeline: true
    language: go
    gitops:
      enabled: true
      base64_encoded_ssh_key: a-base64-encoded-version-of-gh-ssh-public-key-xxxxxxxhbmFsZWN0LmNvbQo=
      base64_encoded_known_hosts: ""
  - name: "example-ns-01"
    exists: false
    createPipeline: true
    language: go
    gitops:
      enabled: true
      base64_encoded_ssh_key: a-base64-encoded-version-of-gh-ssh-public-key-xxxxxxxhbmFsZWN0LmNvbQo=
      base64_encoded_known_hosts: ""
ootb_supply_chains:
  image_prefix: ghrc.io/my-gh-username
  gitops:
    configure: true
    git_writer:
      message: "TAP OSS Based Update of app configuration"
      ssh_user: "git"
      server: "github.com"
      repository: my-gh-username/tap-oss-test
      base64_encoded_ssh_key: a-base64-encoded-version-of-gh-ssh-public-key-xxxxxxxhbmFsZWN0LmNvbQo=
      base64_encoded_known_hosts: ""
      branch: main
      username: analect
      user_email: myemail@email.com
      port: ""
  testing:
    configure: true
EOF
```

In `knative-serving` namespace, it seems the `default-domain` job is failing.  Hence these series of failed pods below.

![image](https://user-images.githubusercontent.com/4063815/152335734-ad3cfd5d-bb0e-4a14-872c-9c6580c4438e.png)

Here are logs from that default-domain-9n4mq.... pod
```
W0202 18:11:55.667588       1 client_config.go:615] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
{"level":"fatal","ts":1643825515.713997,"logger":"fallback.default-domain","caller":"default-domain/main.go:199","msg":"Error finding gateway address","error":"Internal error occurred: failed calling webhook \"webhook.serving.knative.dev\": Post \"https://webhook.knative-serving.svc:443/?timeout=10s\": dial tcp 100.68.14.232:443: connect: connection refused","stacktrace":"main.main\n\tknative.dev/serving/cmd/default-domain/main.go:199\nruntime.main\n\truntime/proc.go:255"}
```
The lens dashboard also shows errors with a series of events (below).  I presume these are related to what's going wrong above.

![image](https://user-images.githubusercontent.com/4063815/152334969-3054ec67-4bf8-4869-a058-ef2031d2d04b.png)

from logs of webhook-6f9bbc48bd-szbp5.16d00b35013550c7
```
{"severity":"WARNING","timestamp":"2022-02-03T11:24:21.581201998Z","logger":"domainmapping-webhook","caller":"webhook/webhook.go:156","message":"server key missing","knative.dev/pod":"domainmapping-webhook-7b4f66bfcd-tz4wl"}
2022/02/03 11:24:21 http: TLS handshake error from 100.96.1.1:33676: tls: no certificates configured
{"severity":"INFO","timestamp":"2022-02-03T11:24:21.934560586Z","logger":"domainmapping-webhook.ValidationWebhook","caller":"controller/controller.go:550","message":"Reconcile succeeded","knative.dev/pod":"domainmapping-webhook-7b4f66bfcd-tz4wl","knative.dev/traceid":"b5d8860e-28b9-4db3-b39f-d85a1e93943c","knative.dev/key":"validation.webhook.domainmapping.serving.knative.dev","duration":"1.318177599s"}
{"severity":"INFO","timestamp":"2022-02-03T11:24:21.967938603Z","logger":"domainmapping-webhook.WebhookCertificates","caller":"controller/controller.go:550","message":"Reconcile succeeded","knative.dev/pod":"domainmapping-webhook-7b4f66bfcd-tz4wl","knative.dev/traceid":"19b6f550-862b-401a-baa9-4f84d6953f31","knative.dev/key":"knative-serving/domainmapping-webhook-certs","duration":"825.528138ms"}
{"severity":"INFO","timestamp":"2022-02-03T11:24:21.969168604Z","logger":"domainmapping-webhook.WebhookCertificates","caller":"controller/controller.go:550","message":"Reconcile succeeded","knative.dev/pod":"domainmapping-webhook-7b4f66bfcd-tz4wl","knative.dev/traceid":"7f45722f-fe03-478f-9909-89a1efffe4eb","knative.dev/key":"knative-serving/domainmapping-webhook-certs","duration":"429.4µs"}
{"severity":"INFO","timestamp":"2022-02-03T11:24:22.165972309Z","logger":"domainmapping-webhook.DefaultingWebhook","caller":"controller/controller.go:550","message":"Reconcile succeeded","knative.dev/pod":"domainmapping-webhook-7b4f66bfcd-tz4wl","knative.dev/traceid":"33b5216b-8ad0-4649-8fd0-b269328df30c","knative.dev/key":"webhook.domainmapping.serving.knative.dev","duration":"1.548315822s"}
{"severity":"INFO","timestamp":"2022-02-03T11:24:22.339594502Z","logger":"domainmapping-webhook.ValidationWebhook","caller":"validation/reconcile_config.go:173","message":"Updating webhook","knative.dev/pod":"domainmapping-webhook-7b4f66bfcd-tz4wl","knative.dev/traceid":"e00bbfa6-2820-463c-8a67-157486719e21","knative.dev/key":"knative-serving/domainmapping-webhook-certs"}
{"severity":"INFO","timestamp":"2022-02-03T11:24:22.458263165Z","logger":"domainmapping-webhook.DefaultingWebhook","caller":"defaulting/defaulting.go:209","message":"Updating webhook","knative.dev/pod":"domainmapping-webhook-7b4f66bfcd-tz4wl","knative.dev/traceid":"40d966ad-93fa-4904-84f6-c523bf6765f6","knative.dev/key":"knative-serving/domainmapping-webhook-certs"}
{"severity":"ERROR","timestamp":"2022-02-03T11:24:22.537699207Z","logger":"domainmapping-webhook.ValidationWebhook","caller":"controller/controller.go:566","message":"Reconcile error","knative.dev/pod":"domainmapping-webhook-7b4f66bfcd-tz4wl","knative.dev/traceid":"e00bbfa6-2820-463c-8a67-157486719e21","knative.dev/key":"knative-serving/domainmapping-webhook-certs","duration":"748.118298ms","error":"failed to update webhook: Operation cannot be fulfilled on validatingwebhookconfigurations.admissionregistration.k8s.io \"validation.webhook.domainmapping.serving.knative.dev\": the object has been modified; please apply your changes to the latest version and try again","stacktrace":"knative.dev/pkg/controller.(*Impl).handleErr\n\tknative.dev/pkg@v0.0.0-20211101212339-96c0204a70dc/controller/controller.go:566\nknative.dev/pkg/controller.(*Impl).processNextWorkItem\n\tknative.dev/pkg@v0.0.0-20211101212339-96c0204a70dc/controller/controller.go:543\nknative.dev/pkg/controller.(*Impl).RunContext.func3\n\tknative.dev/pkg@v0.0.0-20211101212339-96c0204a70dc/controller/controller.go:478"}
{"severity":"INFO","timestamp":"2022-02-03T11:24:22.621009951Z","logger":"domainmapping-webhook.DefaultingWebhook","caller":"controller/controller.go:550","message":"Reconcile succeeded","knative.dev/pod":"domainmapping-webhook-7b4f66bfcd-tz4wl","knative.dev/traceid":"40d966ad-93fa-4904-84f6-c523bf6765f6","knative.dev/key":"knative-serving/domainmapping-webhook-certs","duration":"782.870716ms"}
{"severity":"INFO","timestamp":"2022-02-03T11:24:22.873236085Z","logger":"domainmapping-webhook.ValidationWebhook","caller":"validation/reconcile_config.go:173","message":"Updating webhook","knative.dev/pod":"domainmapping-webhook-7b4f66bfcd-tz4wl","knative.dev/traceid":"7e3a74b2-fbc1-49f5-8e00-ae8d14296a45","knative.dev/key":"validation.webhook.domainmapping.serving.knative.dev"}
{"severity":"INFO","timestamp":"2022-02-03T11:24:23.097294605Z","logger":"domainmapping-webhook.DefaultingWebhook","caller":"defaulting/defaulting.go:209","message":"Updating webhook","knative.dev/pod":"domainmapping-webhook-7b4f66bfcd-tz4wl","knative.dev/traceid":"dc0c1f57-b66f-485d-b1f4-42b3f29d383f","knative.dev/key":"webhook.domainmapping.serving.knative.dev"}
{"severity":"INFO","timestamp":"2022-02-03T11:24:23.204289962Z","logger":"domainmapping-webhook.ValidationWebhook","caller":"validation/reconcile_config.go:173","message":"Updating webhook","knative.dev/pod":"domainmapping-webhook-7b4f66bfcd-tz4wl","knative.dev/traceid":"f8c86b39-2a16-4aa1-8781-b53c548e158f","knative.dev/key":"knative-serving/domainmapping-webhook-certs"}
{"severity":"ERROR","timestamp":"2022-02-03T11:24:23.586435766Z","logger":"domainmapping-webhook.ValidationWebhook","caller":"controller/controller.go:566","message":"Reconcile error","knative.dev/pod":"domainmapping-webhook-7b4f66bfcd-tz4wl","knative.dev/traceid":"7e3a74b2-fbc1-49f5-8e00-ae8d14296a45","knative.dev/key":"validation.webhook.domainmapping.serving.knative.dev","duration":"1.081255177s","error":"failed to update webhook: Operation cannot be fulfilled on validatingwebhookconfigurations.admissionregistration.k8s.io \"validation.webhook.domainmapping.serving.knative.dev\": the object has been modified; please apply your changes to the latest version and try again","stacktrace":"knative.dev/pkg/controller.(*Impl).handleErr\n\tknative.dev/pkg@v0.0.0-20211101212339-96c0204a70dc/controller/controller.go:566\nknative.dev/pkg/controller.(*Impl).processNextWorkItem\n\tknative.dev/pkg@v0.0.0-20211101212339-96c0204a70dc/controller/controller.go:543\nknative.dev/pkg/controller.(*Impl).RunContext.func3\n\tknative.dev/pkg@v0.0.0-20211101212339-96c0204a70dc/controller/controller.go:478"}
{"severity":"INFO","timestamp":"2022-02-03T11:24:23.588201167Z","logger":"domainmapping-webhook.ValidationWebhook","caller":"controller/controller.go:550","message":"Reconcile succeeded","knative.dev/pod":"domainmapping-webhook-7b4f66bfcd-tz4wl","knative.dev/traceid":"f8c86b39-2a16-4aa1-8781-b53c548e158f","knative.dev/key":"knative-serving/domainmapping-webhook-certs","duration":"1.04996866s"}
{"severity":"INFO","timestamp":"2022-02-03T11:24:23.588646067Z","logger":"domainmapping-webhook.DefaultingWebhook","caller":"controller/controller.go:550","message":"Reconcile succeeded","knative.dev/pod":"domainmapping-webhook-7b4f66bfcd-tz4wl","knative.dev/traceid":"dc0c1f57-b66f-485d-b1f4-42b3f29d383f","knative.dev/key":"webhook.domainmapping.serving.knative.dev","duration":"968.137617ms"}
{"severity":"INFO","timestamp":"2022-02-03T11:24:24.86600115Z","logger":"domainmapping-webhook.ValidationWebhook","caller":"validation/reconcile_config.go:173","message":"Updating webhook","knative.dev/pod":"domainmapping-webhook-7b4f66bfcd-tz4wl","knative.dev/traceid":"bbdb5894-984b-49ff-b683-9d3974928cea","knative.dev/key":"knative-serving/domainmapping-webhook-certs"}
{"severity":"INFO","timestamp":"2022-02-03T11:24:24.881670759Z","logger":"domainmapping-webhook.ValidationWebhook","caller":"validation/reconcile_config.go:173","message":"Updating webhook","knative.dev/pod":"domainmapping-webhook-7b4f66bfcd-tz4wl","knative.dev/traceid":"e88045d4-6a62-44b2-8ad6-ce7bddfe4644","knative.dev/key":"validation.webhook.domainmapping.serving.knative.dev"}
{"severity":"INFO","timestamp":"2022-02-03T11:24:25.38609313Z","logger":"domainmapping-webhook.ValidationWebhook","caller":"controller/controller.go:550","message":"Reconcile succeeded","knative.dev/pod":"domainmapping-webhook-7b4f66bfcd-tz4wl","knative.dev/traceid":"bbdb5894-984b-49ff-b683-9d3974928cea","knative.dev/key":"knative-serving/domainmapping-webhook-certs","duration":"1.556064134s"}
{"severity":"INFO","timestamp":"2022-02-03T11:24:25.619670255Z","logger":"domainmapping-webhook.ValidationWebhook","caller":"controller/controller.go:550","message":"Reconcile succeeded","knative.dev/pod":"domainmapping-webhook-7b4f66bfcd-tz4wl","knative.dev/traceid":"e88045d4-6a62-44b2-8ad6-ce7bddfe4644","knative.dev/key":"validation.webhook.domainmapping.serving.knative.dev","duration":"2.032494889s"}
{"severity":"INFO","timestamp":"2022-02-03T11:24:25.775168339Z","logger":"domainmapping-webhook.DefaultingWebhook","caller":"defaulting/defaulting.go:209","message":"Updating webhook","knative.dev/pod":"domainmapping-webhook-7b4f66bfcd-tz4wl","knative.dev/traceid":"e9a67044-0b59-460b-985f-0465ca40e0c0","knative.dev/key":"webhook.domainmapping.serving.knative.dev"}
{"severity":"INFO","timestamp":"2022-02-03T11:24:26.296948319Z","logger":"domainmapping-webhook.ValidationWebhook","caller":"validation/reconcile_config.go:173","message":"Updating webhook","knative.dev/pod":"domainmapping-webhook-7b4f66bfcd-tz4wl","knative.dev/traceid":"6b52f7df-7d5d-45b5-8aa4-53de758681a3","knative.dev/key":"validation.webhook.domainmapping.serving.knative.dev"}
{"severity":"INFO","timestamp":"2022-02-03T11:24:26.589588876Z","logger":"domainmapping-webhook.DefaultingWebhook","caller":"controller/controller.go:550","message":"Reconcile succeeded","knative.dev/pod":"domainmapping-webhook-7b4f66bfcd-tz4wl","knative.dev/traceid":"e9a67044-0b59-460b-985f-0465ca40e0c0","knative.dev/key":"webhook.domainmapping.serving.knative.dev","duration":"1.658744391s"}
{"severity":"INFO","timestamp":"2022-02-03T11:24:26.864547824Z","logger":"domainmapping-webhook.ValidationWebhook","caller":"controller/controller.go:550","message":"Reconcile succeeded","knative.dev/pod":"domainmapping-webhook-7b4f66bfcd-tz4wl","knative.dev/traceid":"6b52f7df-7d5d-45b5-8aa4-53de758681a3","knative.dev/key":"validation.webhook.domainmapping.serving.knative.dev","duration":"1.244367268s"}

```
Any thoughts on what might be going wrong here?  Thanks

**Comment by vrabbi** [comment]
Whats the output of kubectl get svc -A

**Comment by Analect** [comment]
```
~/dev/tce/tap-oss$ kubectl get svc -A
NAMESPACE             NAME                          TYPE           CLUSTER-IP       EXTERNAL-IP   PORT(S)                              AGE
cartographer-system   cartographer-webhook          ClusterIP      100.66.38.51     <none>        443/TCP                              18h
cert-manager          cert-manager                  ClusterIP      100.69.211.208   <none>        9402/TCP                             18h
cert-manager          cert-manager-webhook          ClusterIP      100.71.23.247    <none>        443/TCP                              18h
default               kubernetes                    ClusterIP      100.64.0.1       <none>        443/TCP                              28h
flux-system           source-controller             ClusterIP      100.68.155.40    <none>        80/TCP                               18h
knative-serving       activator-service             ClusterIP      100.71.134.26    <none>        9090/TCP,8008/TCP,80/TCP,81/TCP      18h
knative-serving       autoscaler                    ClusterIP      100.66.9.108     <none>        9090/TCP,8008/TCP,8080/TCP           18h
knative-serving       autoscaler-bucket-00-of-01    ClusterIP      100.66.241.112   <none>        8080/TCP                             18h
knative-serving       controller                    ClusterIP      100.66.201.198   <none>        9090/TCP,8008/TCP                    18h
knative-serving       default-domain-service        ClusterIP      100.65.116.86    <none>        80/TCP                               18h
knative-serving       domainmapping-webhook         ClusterIP      100.65.44.186    <none>        9090/TCP,8008/TCP,443/TCP            18h
knative-serving       net-certmanager-controller    ClusterIP      100.64.209.86    <none>        9090/TCP,8008/TCP                    18h
knative-serving       net-certmanager-webhook       ClusterIP      100.69.198.19    <none>        9090/TCP,8008/TCP,443/TCP            18h
knative-serving       webhook                       ClusterIP      100.68.14.232    <none>        9090/TCP,8008/TCP,443/TCP            18h
kpack                 kpack-webhook                 ClusterIP      100.71.101.227   <none>        443/TCP                              18h
kube-system           antrea                        ClusterIP      100.67.143.78    <none>        443/TCP                              27h
kube-system           kube-dns                      ClusterIP      100.64.0.10      <none>        53/UDP,53/TCP,9153/TCP               28h
kube-system           metrics-server                ClusterIP      100.70.121.35    <none>        443/TCP                              27h
projectcontour        contour                       ClusterIP      100.69.28.237    <none>        8001/TCP                             18h
projectcontour        envoy                         LoadBalancer   100.64.218.204   <pending>     80:31946/TCP,443:30383/TCP           18h
tekton-pipelines      tekton-pipelines-controller   ClusterIP      100.70.85.227    <none>        9090/TCP,8008/TCP,8080/TCP           18h
tekton-pipelines      tekton-pipelines-webhook      ClusterIP      100.68.251.18    <none>        9090/TCP,8008/TCP,443/TCP,8080/TCP   18h
tkg-system            packaging-api                 ClusterIP      100.66.104.254   <none>        443/TCP                              28h

```

**Comment by vrabbi** [comment]
Thats why. Contour isnt getting an ip. I need to add support for clusters without a load balancer

**Comment by vrabbi** [comment]
Ill try and put a fix together today and push up a new version

**Comment by Analect** [comment]
OK. Thanks.

**Comment by vrabbi** [comment]
this has been fixed in version 0.1.2 of the package repository. there is a new section in the values yaml:  
```
contour:
  envoy:
    service:
      type: ClusterIP
```

If you add that to your values file and install a fresh installation it will work. README has been updated as well

**Comment by vrabbi** [comment]
thanks for reporting this and for trying this out! if you have any further issues please let me know and open issues! (PRs are welcome as well :grin: )

**Comment by Analect** [comment]
installed latest version (0.1.2), but somehow knative is still not happy and failing to reconcile.  Also tekton, having previously been `reconcile succeeded` is back to `reconciling`.  Not sure if this suggests lack of resources or not.

```
/dev/tce/tap-oss$ kubectl get pkgi -n tap-oss
NAME                     PACKAGE NAME                     PACKAGE VERSION   DESCRIPTION                                                            AGE
cartographer             cartographer.tap.oss             0.2.1             Reconcile succeeded                                                    14m
cert-manager             cert-manager.tap.oss             1.6.1             Reconcile succeeded                                                    14m
contour                  contour.tap.oss                  1.19.1            Reconcile succeeded                                                    14m
dev-ns-preperation       dev-ns-preperation.tap.oss       0.1.0             Reconcile succeeded                                                    14m
flux-source-controller   flux-source-controller.tap.oss   0.21.1            Reconcile succeeded                                                    14m
knative                  knative-serving.tap.oss          1.0.0             Reconcile failed: Error (see .status.usefulErrorMessage for details)   14m
kpack                    kpack.tap.oss                    0.5.0             Reconcile succeeded                                                    14m
kpack-config             kpack-config.tap.oss             0.5.0             Reconcile succeeded                                                    14m
ootb-supply-chains       ootb-supply-chains.tap.oss       0.1.0             Reconcile succeeded                                                    14m
tap                      tap-install.tap.oss              0.1.1             Reconcile succeeded                                                    14m
tekton-pipelines         tekton.tap.oss                   0.32.1            Reconciling                                                            14m
```
Adding logs from the knative `activator-59cbdb864b-7jr5h` pod below, which seems to be restarting alot.  It complains about not being able to make a connection.

![image](https://user-images.githubusercontent.com/4063815/152373398-d352ccf7-b52f-4585-9c2d-23a892d1be86.png)


```
{"severity":"WARNING","timestamp":"2022-02-03T15:25:28.044813275Z","logger":"activator","caller":"handler/healthz_handler.go:36","message":"Healthcheck failed: connection has not yet been established","commit":"f1e419a","knative.dev/controller":"activator","knative.dev/pod":"activator-59cbdb864b-7jr5h"}
{"severity":"WARNING","timestamp":"2022-02-03T15:25:28.045492977Z","logger":"activator","caller":"handler/healthz_handler.go:36","message":"Healthcheck failed: connection has not yet been established","commit":"f1e419a","knative.dev/controller":"activator","knative.dev/pod":"activator-59cbdb864b-7jr5h"}
{"severity":"ERROR","timestamp":"2022-02-03T15:25:28.41032526Z","logger":"activator","caller":"websocket/connection.go:145","message":"Websocket connection could not be established","commit":"f1e419a","knative.dev/controller":"activator","knative.dev/pod":"activator-59cbdb864b-7jr5h","error":"dial tcp 52.128.23.153:8080: i/o timeout","stacktrace":"knative.dev/pkg/websocket.NewDurableConnection.func1\n\tknative.dev/pkg@v0.0.0-20211101212339-96c0204a70dc/websocket/connection.go:145\nknative.dev/pkg/websocket.(*ManagedConnection).connect.func1\n\tknative.dev/pkg@v0.0.0-20211101212339-96c0204a70dc/websocket/connection.go:226\nk8s.io/apimachinery/pkg/util/wait.runConditionWithCrashProtection\n\tk8s.io/apimachinery@v0.21.4/pkg/util/wait/wait.go:211\nk8s.io/apimachinery/pkg/util/wait.ExponentialBackoff\n\tk8s.io/apimachinery@v0.21.4/pkg/util/wait/wait.go:399\nknative.dev/pkg/websocket.(*ManagedConnection).connect\n\tknative.dev/pkg@v0.0.0-20211101212339-96c0204a70dc/websocket/connection.go:223\nknative.dev/pkg/websocket.NewDurableConnection.func2\n\tknative.dev/pkg@v0.0.0-20211101212339-96c0204a70dc/websocket/connection.go:163"}
{"severity":"ERROR","timestamp":"2022-02-03T15:25:28.41042556Z","logger":"activator","caller":"websocket/connection.go:164","message":"Failed connecting to ws://autoscaler.knative-serving.svc.cluster.local:8080","commit":"f1e419a","knative.dev/controller":"activator","knative.dev/pod":"activator-59cbdb864b-7jr5h","error":"timed out waiting for the condition","stacktrace":"knative.dev/pkg/websocket.NewDurableConnection.func2\n\tknative.dev/pkg@v0.0.0-20211101212339-96c0204a70dc/websocket/connection.go:164"}
{"severity":"INFO","timestamp":"2022-02-03T15:25:28.41045626Z","logger":"activator","caller":"websocket/connection.go:162","message":"Connecting to ws://autoscaler.knative-serving.svc.cluster.local:8080","commit":"f1e419a","knative.dev/controller":"activator","knative.dev/pod":"activator-59cbdb864b-7jr5h"}
{"severity":"ERROR","timestamp":"2022-02-03T15:25:30.25753874Z","logger":"activator","caller":"websocket/connection.go:192","message":"Failed to send ping message to ws://autoscaler.knative-serving.svc.cluster.local:8080","commit":"f1e419a","knative.dev/controller":"activator","knative.dev/pod":"activator-59cbdb864b-7jr5h","error":"connection has not yet been established","stacktrace":"knative.dev/pkg/websocket.NewDurableConnection.func3\n\tknative.dev/pkg@v0.0.0-20211101212339-96c0204a70dc/websocket/connection.go:192"}
{"severity":"ERROR","timestamp":"2022-02-03T15:25:31.411233351Z","logger":"activator","caller":"websocket/connection.go:145","message":"Websocket connection could not be established","commit":"f1e419a","knative.dev/controller":"activator","knative.dev/pod":"activator-59cbdb864b-7jr5h","error":"dial tcp 52.128.23.153:8080: i/o timeout","stacktrace":"knative.dev/pkg/websocket.NewDurableConnection.func1\n\tknative.dev/pkg@v0.0.0-20211101212339-96c0204a70dc/websocket/connection.go:145\nknative.dev/pkg/websocket.(*ManagedConnection).connect.func1\n\tknative.dev/pkg@v0.0.0-20211101212339-96c0204a70dc/websocket/connection.go:226\nk8s.io/apimachinery/pkg/util/wait.runConditionWithCrashProtection\n\tk8s.io/apimachinery@v0.21.4/pkg/util/wait/wait.go:211\nk8s.io/apimachinery/pkg/util/wait.ExponentialBackoff\n\tk8s.io/apimachinery@v0.21.4/pkg/util/wait/wait.go:399\nknative.dev/pkg/websocket.(*ManagedConnection).connect\n\tknative.dev/pkg@v0.0.0-20211101212339-96c0204a70dc/websocket/connection.go:223\nknative.dev/pkg/websocket.NewDurableConnection.func2\n\tknative.dev/pkg@v0.0.0-20211101212339-96c0204a70dc/websocket/connection.go:163"}
{"severity":"ERROR","timestamp":"2022-02-03T15:25:33.588606622Z","logger":"activator","caller":"websocket/connection.go:192","message":"Failed to send ping message to ws://autoscaler.knative-serving.svc.cluster.local:8080","commit":"f1e419a","knative.dev/controller":"activator","knative.dev/pod":"activator-59cbdb864b-7jr5h","error":"connection has not yet been established","stacktrace":"knative.dev/pkg/websocket.NewDurableConnection.func3\n\tknative.dev/pkg@v0.0.0-20211101212339-96c0204a70dc/websocket/connection.go:192"}
{"severity":"ERROR","timestamp":"2022-02-03T15:25:34.572708377Z","logger":"activator","caller":"websocket/connection.go:145","message":"Websocket connection could not be established","commit":"f1e419a","knative.dev/controller":"activator","knative.dev/pod":"activator-59cbdb864b-7jr5h","error":"dial tcp 52.128.23.153:8080: i/o timeout","stacktrace":"knative.dev/pkg/websocket.NewDurableConnection.func1\n\tknative.dev/pkg@v0.0.0-20211101212339-96c0204a70dc/websocket/connection.go:145\nknative.dev/pkg/websocket.(*ManagedConnection).connect.func1\n\tknative.dev/pkg@v0.0.0-20211101212339-96c0204a70dc/websocket/connection.go:226\nk8s.io/apimachinery/pkg/util/wait.runConditionWithCrashProtection\n\tk8s.io/apimachinery@v0.21.4/pkg/util/wait/wait.go:211\nk8s.io/apimachinery/pkg/util/wait.ExponentialBackoff\n\tk8s.io/apimachinery@v0.21.4/pkg/util/wait/wait.go:399\nknative.dev/pkg/websocket.(*ManagedConnection).connect\n\tknative.dev/pkg@v0.0.0-20211101212339-96c0204a70dc/websocket/connection.go:223\nknative.dev/pkg/websocket.NewDurableConnection.func2\n\tknative.dev/pkg@v0.0.0-20211101212339-96c0204a70dc/websocket/connection.go:163"}
{"severity":"ERROR","timestamp":"2022-02-03T15:25:36.922704516Z","logger":"activator","caller":"websocket/connection.go:192","message":"Failed to send ping message to ws://autoscaler.knative-serving.svc.cluster.local:8080","commit":"f1e419a","knative.dev/controller":"activator","knative.dev/pod":"activator-59cbdb864b-7jr5h","error":"connection has not yet been established","stacktrace":"knative.dev/pkg/websocket.NewDurableConnection.func3\n\tknative.dev/pkg@v0.0.0-20211101212339-96c0204a70dc/websocket/connection.go:192"}
{"severity":"ERROR","timestamp":"2022-02-03T15:25:37.726668586Z","logger":"activator","caller":"websocket/connection.go:145","message":"Websocket connection could not be established","commit":"f1e419a","knative.dev/controller":"activator","knative.dev/pod":"activator-59cbdb864b-7jr5h","error":"dial tcp 52.128.23.153:8080: i/o timeout","stacktrace":"knative.dev/pkg/websocket.NewDurableConnection.func1\n\tknative.dev/pkg@v0.0.0-20211101212339-96c0204a70dc/websocket/connection.go:145\nknative.dev/pkg/websocket.(*ManagedConnection).connect.func1\n\tknative.dev/pkg@v0.0.0-20211101212339-96c0204a70dc/websocket/connection.go:226\nk8s.io/apimachinery/pkg/util/wait.runConditionWithCrashProtection\n\tk8s.io/apimachinery@v0.21.4/pkg/util/wait/wait.go:211\nk8s.io/apimachinery/pkg/util/wait.ExponentialBackoff\n\tk8s.io/apimachinery@v0.21.4/pkg/util/wait/wait.go:399\nknative.dev/pkg/websocket.(*ManagedConnection).connect\n\tknative.dev/pkg@v0.0.0-20211101212339-96c0204a70dc/websocket/connection.go:223\nknative.dev/pkg/websocket.NewDurableConnection.func2\n\tknative.dev/pkg@v0.0.0-20211101212339-96c0204a70dc/websocket/connection.go:163"}
{"severity":"WARNING","timestamp":"2022-02-03T15:25:38.031792009Z","logger":"activator","caller":"handler/healthz_handler.go:36","message":"Healthcheck failed: connection has not yet been established","commit":"f1e419a","knative.dev/controller":"activator","knative.dev/pod":"activator-59cbdb864b-7jr5h"}
{"severity":"WARNING","timestamp":"2022-02-03T15:25:38.03218091Z","logger":"activator","caller":"handler/healthz_handler.go:36","message":"Healthcheck failed: connection has not yet been established","commit":"f1e419a","knative.dev/controller":"activator","knative.dev/pod":"activator-59cbdb864b-7jr5h"}
{"severity":"INFO","timestamp":"2022-02-03T15:25:38.105354008Z","logger":"activator","caller":"activator/main.go:249","message":"Received SIGTERM","commit":"f1e419a","knative.dev/controller":"activator","knative.dev/pod":"activator-59cbdb864b-7jr5h"}
{"severity":"INFO","timestamp":"2022-02-03T15:25:38.105468308Z","logger":"activator","caller":"activator/main.go:258","message":"Sleeping 45s to allow K8s propagation of non-ready state","commit":"f1e419a","knative.dev/controller":"activator","knative.dev/pod":"activator-59cbdb864b-7jr5h"}
{"severity":"ERROR","timestamp":"2022-02-03T15:25:40.256788914Z","logger":"activator","caller":"websocket/connection.go:192","message":"Failed to send ping message to ws://autoscaler.knative-serving.svc.cluster.local:8080","commit":"f1e419a","knative.dev/controller":"activator","knative.dev/pod":"activator-59cbdb864b-7jr5h","error":"connection has not yet been established","stacktrace":"knative.dev/pkg/websocket.NewDurableConnection.func3\n\tknative.dev/pkg@v0.0.0-20211101212339-96c0204a70dc/websocket/connection.go:192"}
{"severity":"ERROR","timestamp":"2022-02-03T15:25:40.923044012Z","logger":"activator","caller":"websocket/connection.go:145","message":"Websocket connection could not be established","commit":"f1e419a","knative.dev/controller":"activator","knative.dev/pod":"activator-59cbdb864b-7jr5h","error":"dial tcp 52.128.23.153:8080: i/o timeout","stacktrace":"knative.dev/pkg/websocket.NewDurableConnection.func1\n\tknative.dev/pkg@v0.0.0-20211101212339-96c0204a70dc/websocket/connection.go:145\nknative.dev/pkg/websocket.(*ManagedConnection).connect.func1\n\tknative.dev/pkg@v0.0.0-20211101212339-96c0204a70dc/websocket/connection.go:226\nk8s.io/apimachinery/pkg/util/wait.runConditionWithCrashProtection\n\tk8s.io/apimachinery@v0.21.4/pkg/util/wait/wait.go:211\nk8s.io/apimachinery/pkg/util/wait.ExponentialBackoff\n\tk8s.io/apimachinery@v0.21.4/pkg/util/wait/wait.go:399\nknative.dev/pkg/websocket.(*ManagedConnection).connect\n\tknative.dev/pkg@v0.0.0-20211101212339-96c0204a70dc/websocket/connection.go:223\nknative.dev/pkg/websocket.NewDurableConnection.func2\n\tknative.dev/pkg@v0.0.0-20211101212339-96c0204a70dc/websocket/connection.go:163"}
{"severity":"ERROR","timestamp":"2022-02-03T15:25:43.58917861Z","logger":"activator","caller":"websocket/connection.go:192","message":"Failed to send ping message to ws://autoscaler.knative-serving.svc.cluster.local:8080","commit":"f1e419a","knative.dev/controller":"activator","knative.dev/pod":"activator-59cbdb864b-7jr5h","error":"connection has not yet been established","stacktrace":"knative.dev/pkg/websocket.NewDurableConnection.func3\n\tknative.dev/pkg@v0.0.0-20211101212339-96c0204a70dc/websocket/connection.go:192"}
{"severity":"ERROR","timestamp":"2022-02-03T15:25:44.227495333Z","logger":"activator","caller":"websocket/connection.go:145","message":"Websocket connection could not be established","commit":"f1e419a","knative.dev/controller":"activator","knative.dev/pod":"activator-59cbdb864b-7jr5h","error":"dial tcp 52.128.23.153:8080: i/o timeout","stacktrace":"knative.dev/pkg/websocket.NewDurableConnection.func1\n\tknative.dev/pkg@v0.0.0-20211101212339-96c0204a70dc/websocket/connection.go:145\nknative.dev/pkg/websocket.(*ManagedConnection).connect.func1\n\tknative.dev/pkg@v0.0.0-20211101212339-96c0204a70dc/websocket/connection.go:226\nk8s.io/apimachinery/pkg/util/wait.runConditionWithCrashProtection\n\tk8s.io/apimachinery@v0.21.4/pkg/util/wait/wait.go:211\nk8s.io/apimachinery/pkg/util/wait.ExponentialBackoff\n\tk8s.io/apimachinery@v0.21.4/pkg/util/wait/wait.go:399\nknative.dev/pkg/websocket.(*ManagedConnection).connect\n\tknative.dev/pkg@v0.0.0-20211101212339-96c0204a70dc/websocket/connection.go:223\nknative.dev/pkg/websocket.NewDurableConnection.func2\n\tknative.dev/pkg@v0.0.0-20211101212339-96c0204a70dc/websocket/connection.go:163"}
{"severity":"ERROR","timestamp":"2022-02-03T15:25:46.922763012Z","logger":"activator","caller":"websocket/connection.go:192","message":"Failed to send ping message to ws://autoscaler.knative-serving.svc.cluster.local:8080","commit":"f1e419a","knative.dev/controller":"activator","knative.dev/pod":"activator-59cbdb864b-7jr5h","error":"connection has not yet been established","stacktrace":"knative.dev/pkg/websocket.NewDurableConnection.func3\n\tknative.dev/pkg@v0.0.0-20211101212339-96c0204a70dc/websocket/connection.go:192"}
{"severity":"ERROR","timestamp":"2022-02-03T15:25:47.5479088Z","logger":"activator","caller":"websocket/connection.go:145","message":"Websocket connection could not be established","commit":"f1e419a","knative.dev/controller":"activator","knative.dev/pod":"activator-59cbdb864b-7jr5h","error":"dial tcp 52.128.23.153:8080: i/o timeout","stacktrace":"knative.dev/pkg/websocket.NewDurableConnection.func1\n\tknative.dev/pkg@v0.0.0-20211101212339-96c0204a70dc/websocket/connection.go:145\nknative.dev/pkg/websocket.(*ManagedConnection).connect.func1\n\tknative.dev/pkg@v0.0.0-20211101212339-96c0204a70dc/websocket/connection.go:226\nk8s.io/apimachinery/pkg/util/wait.runConditionWithCrashProtection\n\tk8s.io/apimachinery@v0.21.4/pkg/util/wait/wait.go:211\nk8s.io/apimachinery/pkg/util/wait.ExponentialBackoff\n\tk8s.io/apimachinery@v0.21.4/pkg/util/wait/wait.go:399\nknative.dev/pkg/websocket.(*ManagedConnection).connect\n\tknative.dev/pkg@v0.0.0-20211101212339-96c0204a70dc/websocket/connection.go:223\nknative.dev/pkg/websocket.NewDurableConnection.func2\n\tknative.dev/pkg@v0.0.0-20211101212339-96c0204a70dc/websocket/connection.go:163"}
{"severity":"INFO","timestamp":"2022-02-03T15:25:48.028730299Z","logger":"activator","caller":"activator/main.go:276","message":"Signal context canceled","commit":"f1e419a","knative.dev/controller":"activator","knative.dev/pod":"activator-59cbdb864b-7jr5h"}
{"severity":"WARNING","timestamp":"2022-02-03T15:25:48.028807699Z","logger":"activator","caller":"handler/healthz_handler.go:36","message":"Healthcheck failed: received SIGTERM from kubelet","commit":"f1e419a","knative.dev/controller":"activator","knative.dev/pod":"activator-59cbdb864b-7jr5h"}
{"severity":"ERROR","timestamp":"2022-02-03T15:25:50.25755692Z","logger":"activator","caller":"websocket/connection.go:192","message":"Failed to send ping message to ws://autoscaler.knative-serving.svc.cluster.local:8080","commit":"f1e419a","knative.dev/controller":"activator","knative.dev/pod":"activator-59cbdb864b-7jr5h","error":"connection has not yet been established","stacktrace":"knative.dev/pkg/websocket.NewDurableConnection.func3\n\tknative.dev/pkg@v0.0.0-20211101212339-96c0204a70dc/websocket/connection.go:192"}
{"severity":"ERROR","timestamp":"2022-02-03T15:25:51.081930748Z","logger":"activator","caller":"websocket/connection.go:145","message":"Websocket connection could not be established","commit":"f1e419a","knative.dev/controller":"activator","knative.dev/pod":"activator-59cbdb864b-7jr5h","error":"dial tcp 52.128.23.153:8080: i/o timeout","stacktrace":"knative.dev/pkg/websocket.NewDurableConnection.func1\n\tknative.dev/pkg@v0.0.0-20211101212339-96c0204a70dc/websocket/connection.go:145\nknative.dev/pkg/websocket.(*ManagedConnection).connect.func1\n\tknative.dev/pkg@v0.0.0-20211101212339-96c0204a70dc/websocket/connection.go:226\nk8s.io/apimachinery/pkg/util/wait.runConditionWithCrashProtection\n\tk8s.io/apimachinery@v0.21.4/pkg/util/wait/wait.go:211\nk8s.io/apimachinery/pkg/util/wait.ExponentialBackoff\n\tk8s.io/apimachinery@v0.21.4/pkg/util/wait/wait.go:399\nknative.dev/pkg/websocket.(*ManagedConnection).connect\n\tknative.dev/pkg@v0.0.0-20211101212339-96c0204a70dc/websocket/connection.go:223\nknative.dev/pkg/websocket.NewDurableConnection.func2\n\tknative.dev/pkg@v0.0.0-20211101212339-96c0204a70dc/websocket/connection.go:163"}
{"severity":"ERROR","timestamp":"2022-02-03T15:25:53.592437933Z","logger":"activator","caller":"websocket/connection.go:192","message":"Failed to send ping message to ws://autoscaler.knative-serving.svc.cluster.local:8080","commit":"f1e419a","knative.dev/controller":"activator","knative.dev/pod":"activator-59cbdb864b-7jr5h","error":"connection has not yet been established","stacktrace":"knative.dev/pkg/websocket.NewDurableConnection.func3\n\tknative.dev/pkg@v0.0.0-20211101212339-96c0204a70dc/websocket/connection.go:192"}
{"severity":"ERROR","timestamp":"2022-02-03T15:25:54.735908824Z","logger":"activator","caller":"websocket/connection.go:145","message":"Websocket connection could not be established","commit":"f1e419a","knative.dev/controller":"activator","knative.dev/pod":"activator-59cbdb864b-7jr5h","error":"dial tcp 52.128.23.153:8080: i/o timeout","stacktrace":"knative.dev/pkg/websocket.NewDurableConnection.func1\n\tknative.dev/pkg@v0.0.0-20211101212339-96c0204a70dc/websocket/connection.go:145\nknative.dev/pkg/websocket.(*ManagedConnection).connect.func1\n\tknative.dev/pkg@v0.0.0-20211101212339-96c0204a70dc/websocket/connection.go:226\nk8s.io/apimachinery/pkg/util/wait.runConditionWithCrashProtection\n\tk8s.io/apimachinery@v0.21.4/pkg/util/wait/wait.go:211\nk8s.io/apimachinery/pkg/util/wait.ExponentialBackoff\n\tk8s.io/apimachinery@v0.21.4/pkg/util/wait/wait.go:399\nknative.dev/pkg/websocket.(*ManagedConnection).connect\n\tknative.dev/pkg@v0.0.0-20211101212339-96c0204a70dc/websocket/connection.go:223\nknative.dev/pkg/websocket.NewDurableConnection.func2\n\tknative.dev/pkg@v0.0.0-20211101212339-96c0204a70dc/websocket/connection.go:163"}
{"severity":"ERROR","timestamp":"2022-02-03T15:25:56.923854439Z","logger":"activator","caller":"websocket/connection.go:192","message":"Failed to send ping message to ws://autoscaler.knative-serving.svc.cluster.local:8080","commit":"f1e419a","knative.dev/controller":"activator","knative.dev/pod":"activator-59cbdb864b-7jr5h","error":"connection has not yet been established","stacktrace":"knative.dev/pkg/websocket.NewDurableConnection.func3\n\tknative.dev/pkg@v0.0.0-20211101212339-96c0204a70dc/websocket/connection.go:192"}
{"severity":"WARNING","timestamp":"2022-02-03T15:25:58.031679535Z","logger":"activator","caller":"handler/healthz_handler.go:36","message":"Healthcheck failed: received SIGTERM from kubelet","commit":"f1e419a","knative.dev/controller":"activator","knative.dev/pod":"activator-59cbdb864b-7jr5h"}
{"severity":"ERROR","timestamp":"2022-02-03T15:25:58.537883304Z","logger":"activator","caller":"websocket/connection.go:145","message":"Websocket connection could not be established","commit":"f1e419a","knative.dev/controller":"activator","knative.dev/pod":"activator-59cbdb864b-7jr5h","error":"dial tcp 52.128.23.153:8080: i/o timeout","stacktrace":"knative.dev/pkg/websocket.NewDurableConnection.func1\n\tknative.dev/pkg@v0.0.0-20211101212339-96c0204a70dc/websocket/connection.go:145\nknative.dev/pkg/websocket.(*ManagedConnection).connect.func1\n\tknative.dev/pkg@v0.0.0-20211101212339-96c0204a70dc/websocket/connection.go:226\nk8s.io/apimachinery/pkg/util/wait.runConditionWithCrashProtection\n\tk8s.io/apimachinery@v0.21.4/pkg/util/wait/wait.go:211\nk8s.io/apimachinery/pkg/util/wait.ExponentialBackoff\n\tk8s.io/apimachinery@v0.21.4/pkg/util/wait/wait.go:399\nknative.dev/pkg/websocket.(*ManagedConnection).connect\n\tknative.dev/pkg@v0.0.0-20211101212339-96c0204a70dc/websocket/connection.go:223\nknative.dev/pkg/websocket.NewDurableConnection.func2\n\tknative.dev/pkg@v0.0.0-20211101212339-96c0204a70dc/websocket/connection.go:163"}
{"severity":"ERROR","timestamp":"2022-02-03T15:26:00.255179748Z","logger":"activator","caller":"websocket/connection.go:192","message":"Failed to send ping message to ws://autoscaler.knative-serving.svc.cluster.local:8080","commit":"f1e419a","knative.dev/controller":"activator","knative.dev/pod":"activator-59cbdb864b-7jr5h","error":"connection has not yet been established","stacktrace":"knative.dev/pkg/websocket.NewDurableConnection.func3\n\tknative.dev/pkg@v0.0.0-20211101212339-96c0204a70dc/websocket/connection.go:192"}
{"severity":"ERROR","timestamp":"2022-02-03T15:26:02.367887364Z","logger":"activator","caller":"websocket/connection.go:145","message":"Websocket connection could not be established","commit":"f1e419a","knative.dev/controller":"activator","knative.dev/pod":"activator-59cbdb864b-7jr5h","error":"dial tcp 52.128.23.153:8080: i/o timeout","stacktrace":"knative.dev/pkg/websocket.NewDurableConnection.func1\n\tknative.dev/pkg@v0.0.0-20211101212339-96c0204a70dc/websocket/connection.go:145\nknative.dev/pkg/websocket.(*ManagedConnection).connect.func1\n\tknative.dev/pkg@v0.0.0-20211101212339-96c0204a70dc/websocket/connection.go:226\nk8s.io/apimachinery/pkg/util/wait.runConditionWithCrashProtection\n\tk8s.io/apimachinery@v0.21.4/pkg/util/wait/wait.go:211\nk8s.io/apimachinery/pkg/util/wait.ExponentialBackoff\n\tk8s.io/apimachinery@v0.21.4/pkg/util/wait/wait.go:399\nknative.dev/pkg/websocket.(*ManagedConnection).connect\n\tknative.dev/pkg@v0.0.0-20211101212339-96c0204a70dc/websocket/connection.go:223\nknative.dev/pkg/websocket.NewDurableConnection.func2\n\tknative.dev/pkg@v0.0.0-20211101212339-96c0204a70dc/websocket/connection.go:163"}
{"severity":"ERROR","timestamp":"2022-02-03T15:26:03.589775469Z","logger":"activator","caller":"websocket/connection.go:192","message":"Failed to send ping message to ws://autoscaler.knative-serving.svc.cluster.local:8080","commit":"f1e419a","knative.dev/controller":"activator","knative.dev/pod":"activator-59cbdb864b-7jr5h","error":"connection has not yet been established","stacktrace":"knative.dev/pkg/websocket.NewDurableConnection.func3\n\tknative.dev/pkg@v0.0.0-20211101212339-96c0204a70dc/websocket/connection.go:192"}
Logs from 2/3/202
```

**Comment by Analect** [comment]
installed latest version (0.1.4) but still having trouble to get knative stable and working.  Using these settings in values yaml

```
contour:
  envoy:
    service:
      type: ClusterIP
knative:
  domain:
    name: local.projectcontour.io
    type: real
```
Of the pods in `knative-serving` namespace, 3 in particular are having CrashLoopBackOff problems ... 

```
~/dev/tce/tap-oss$ kubectl get deployments -n knative-serving
NAME                         READY   UP-TO-DATE   AVAILABLE   AGE
activator                    0/1     1            0           46m
autoscaler                   1/1     1            1           46m
controller                   1/1     1            1           46m
domain-mapping               1/1     1            1           46m
domainmapping-webhook        1/1     1            1           46m
net-certmanager-controller   1/1     1            1           46m
net-certmanager-webhook      1/1     1            1           46m
net-contour-controller       1/1     1            1           46m
webhook                      0/1     1            0           46m
```

* activator-xxx
* domainmapping-webhook-xxx
* webhook-xxx

Some logs from each, for what it's worth

activator
```
ctivator
{"severity":"ERROR","timestamp":"2022-02-04T16:11:38.854560106Z","logger":"activator","caller":"websocket/connection.go:145","message":"Websocket connection could not be established","commit":"f1e419a","knative.dev/controller":"activator","knative.dev/pod":"activator-69cdd68786-4vxkx","error":"dial tcp 52.128.23.153:8080: i/o timeout","stacktrace":"knative.dev/pkg/websocket.NewDurableConnection.func1\n\tknative.dev/pkg@v0.0.0-20211101212339-96c0204a70dc/websocket/connection.go:145\nknative.dev/pkg/websocket.(*ManagedConnection).connect.func1\n\tknative.dev/pkg@v0.0.0-20211101212339-96c0204a70dc/websocket/connection.go:226\nk8s.io/apimachinery/pkg/util/wait.runConditionWithCrashProtection\n\tk8s.io/apimachinery@v0.21.4/pkg/util/wait/wait.go:211\nk8s.io/apimachinery/pkg/util/wait.ExponentialBackoff\n\tk8s.io/apimachinery@v0.21.4/pkg/util/wait/wait.go:399\nknative.dev/pkg/websocket.(*ManagedConnection).connect\n\tknative.dev/pkg@v0.0.0-20211101212339-96c0204a70dc/websocket/connection.go:223\nknative.dev/pkg/websocket.NewDurableConnection.func2\n\tknative.dev/pkg@v0.0.0-20211101212339-96c0204a70dc/websocket/connection.go:163"}
activator
{"severity":"ERROR","timestamp":"2022-02-04T16:11:41.050996142Z","logger":"activator","caller":"websocket/connection.go:192","message":"Failed to send ping message to ws://autoscaler.knative-serving.svc.cluster.local:8080","commit":"f1e419a","knative.dev/controller":"activator","knative.dev/pod":"activator-69cdd68786-4vxkx","error":"connection has not yet been established","stacktrace":"knative.dev/pkg/websocket.NewDurableConnection.func3\n\tknative.dev/pkg@v0.0.0-20211101212339-96c0204a70dc/websocket/connection.go:192"}
activator
{"severity":"ERROR","timestamp":"2022-02-04T16:11:44.395640261Z","logger":"activator","caller":"websocket/connection.go:192","message":"Failed to send ping message to ws://autoscaler.knative-serving.svc.cluster.local:8080","commit":"f1e419a","knative.dev/controller":"activator","knative.dev/pod":"activator-69cdd68786-4vxkx","error":"connection has not yet been established","stacktrace":"knative.dev/pkg/websocket.NewDurableConnection.func3\n\tknative.dev/pkg@v0.0.0-20211101212339-96c0204a70dc/websocket/connection.go:192"}
activator
{"severity":"ERROR","timestamp":"2022-02-04T16:11:44.522037034Z","logger":"activator","caller":"websocket/connection.go:145","message":"Websocket connection could not be established","commit":"f1e419a","knative.dev/controller":"activator","knative.dev/pod":"activator-69cdd68786-4vxkx","error":"dial tcp 52.128.23.153:8080: i/o timeout","stacktrace":"knative.dev/pkg/websocket.NewDurableConnection.func1\n\tknative.dev/pkg@v0.0.0-20211101212339-96c0204a70dc/websocket/connection.go:145\nknative.dev/pkg/websocket.(*ManagedConnection).connect.func1\n\tknative.dev/pkg@v0.0.0-20211101212339-96c0204a70dc/websocket/connection.go:226\nk8s.io/apimachinery/pkg/util/wait.runConditionWithCrashProtection\n\tk8s.io/apimachinery@v0.21.4/pkg/util/wait/wait.go:211\nk8s.io/apimachinery/pkg/util/wait.ExponentialBackoff\n\tk8s.io/apimachinery@v0.21.4/pkg/util/wait/wait.go:399\nknative.dev/pkg/websocket.(*ManagedConnection).connect\n\tknative.dev/pkg@v0.0.0-20211101212339-96c0204a70dc/websocket/connection.go:223\nknative.dev/pkg/websocket.NewDurableConnection.func2\n\tknative.dev/pkg@v0.0.0-20211101212339-96c0204a70dc/websocket/connection.go:163"}
activator
{"severity":"WARNING","timestamp":"2022-02-04T16:11:47.497364962Z","logger":"activator","caller":"handler/healthz_handler.go:36","message":"Healthcheck failed: received SIGTERM from kubelet","commit":"f1e419a","knative.dev/controller":"activator","knative.dev/pod":"activator-69cdd68786-4vxkx"}
activator
{"severity":"ERROR","timestamp":"2022-02-04T16:11:47.725024654Z","logger":"activator","caller":"websocket/connection.go:192","message":"Failed to send ping message to ws://autoscaler.knative-serving.svc.cluster.local:8080","commit":"f1e419a","knative.dev/controller":"activator","knative.dev/pod":"activator-69cdd68786-4vxkx","error":"connection has not yet been established","stacktrace":"knative.dev/pkg/websocket.NewDurableConnection.func3\n\tknative.dev/pkg@v0.0.0-20211101212339-96c0204a70dc/websocket/connection.go:192"}
activator
{"severity":"ERROR","timestamp":"2022-02-04T16:11:49.978382526Z","logger":"activator","caller":"websocket/connection.go:145","message":"Websocket connection could not be established","commit":"f1e419a","knative.dev/controller":"activator","knative.dev/pod":"activator-69cdd68786-4vxkx","error":"dial tcp 52.128.23.153:8080: i/o timeout","stacktrace":"knative.dev/pkg/websocket.NewDurableConnection.func1\n\tknative.dev/pkg@v0.0.0-20211101212339-96c0204a70dc/websocket/connection.go:145\nknative.dev/pkg/websocket.(*ManagedConnection).connect.func1\n\tknative.dev/pkg@v0.0.0-20211101212339-96c0204a70dc/websocket/connection.go:226\nk8s.io/apimachinery/pkg/util/wait.runConditionWithCrashProtection\n\tk8s.io/apimachinery@v0.21.4/pkg/util/wait/wait.go:211\nk8s.io/apimachinery/pkg/util/wait.ExponentialBackoff\n\tk8s.io/apimachinery@v0.21.4/pkg/util/wait/wait.go:399\nknative.dev/pkg/websocket.(*ManagedConnection).connect\n\tknative.dev/pkg@v0.0.0-20211101212339-96c0204a70dc/websocket/connection.go:223\nknative.dev/pkg/websocket.NewDurableConnection.func2\n\tknative.dev/pkg@v0.0.0-20211101212339-96c0204a70dc/websocket/connection.go:163"}
activator
{"severity":"ERROR","timestamp":"2022-02-04T16:11:51.057680162Z","logger":"activator","caller":"websocket/connection.go:192","message":"Failed to send ping message to ws://autoscaler.knative-serving.svc.cluster.local:8080","commit":"f1e419a","knative.dev/controller":"activator","knative.dev/pod":"activator-69cdd68786-4vxkx","error":"connection has not yet been established","stacktrace":"knative.dev/pkg/websocket.NewDurableConnection.func3\n\tknative.dev/pkg@v0.0.0-20211101212339-96c0204a70dc/websocket/connection.go:192"}
```

domain-mapping-webook
```
domainmapping-webhook
2022/02/04 16:03:39 Registering 2 clients
domainmapping-webhook
2022/02/04 16:03:39 Registering 2 informer factories
domainmapping-webhook
2022/02/04 16:03:39 Registering 3 informers
domainmapping-webhook
2022/02/04 16:03:39 Registering 3 controllers
domainmapping-webhook
2022/02/04 16:03:46 Error reading/parsing logging configuration: timed out waiting for the condition: configmaps "config-logging" is forbidden: User "system:serviceaccount:knative-serving:controller" cannot get resource "configmaps" in API group "" in the namespace "knative-serving"
```

webhook
```
ebhook
2022/02/04 16:10:09 http: TLS handshake error from 100.96.1.1:53616: tls: no certificates configured
webhook
{"severity":"WARNING","timestamp":"2022-02-04T16:10:11.079240209Z","logger":"webhook","caller":"webhook/webhook.go:156","message":"server key missing","commit":"f1e419a","knative.dev/pod":"webhook-6c75d98465-v7zt2"}
webhook
2022/02/04 16:10:11 http: TLS handshake error from 100.96.1.1:53618: tls: no certificates configured
webhook
{"severity":"WARNING","timestamp":"2022-02-04T16:10:11.895359016Z","logger":"webhook","caller":"webhook/webhook.go:156","message":"server key missing","commit":"f1e419a","knative.dev/pod":"webhook-6c75d98465-v7zt2"}
webhook
2022/02/04 16:10:11 http: TLS handshake error from 100.96.1.1:53620: tls: no certificates configured
webhook
{"severity":"WARNING","timestamp":"2022-02-04T16:10:12.888638594Z","logger":"webhook","caller":"webhook/webhook.go:156","message":"server key missing","commit":"f1e419a","knative.dev/pod":"webhook-6c75d98465-v7zt2"}
```

**Comment by vrabbi** [comment]
can you try with the latest 0.2.1 release? i am not able to reproduce the issue but have made alot of changes to the packages so worth trying. also added new packages and customizations.

**Comment by Analect** [comment]
See a possible resolution I arrived at here: https://github.com/vrabbi/tap-oss/issues/4#issuecomment-1045999348
